name: Atualização do Rank de FIIs

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 12 * * *'

jobs:
  update_ranking:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build . -t olheiro-fii-ranker

      - name: Run the Ranking Script
        run: docker run --rm -v ${{ github.workspace }}:/app olheiro-fii-ranker

      - name: Update README with Top FIIs
        run: |
          python -m pip install pandas
          python .github/scripts/update_readme.py

      - name: Remove other changed files (except README.md)
        run: |
          git reset --hard  # Descarta todas as alterações não comitadas
          git checkout HEAD README.md  # Restaura apenas o README.md para o estado atual

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update FII ranking and README