name: FII Ranking Update

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 12 * * *'

jobs:
  update_ranking:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build . -t olheiro-fii-ranker

      - name: Run the Ranking Script
        run: docker run --rm -v ${{ github.workspace }}:/app olheiro-fii-ranker

      - name: Update README with Top FIIs
        run: |
          python -m pip install pandas tabulate
          python .github/scripts/update_readme.py

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: olheiro_bot
          commit_message: 'docs: update README with latest top FIIs'
          file_pattern: README.md